const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const today=new Date();const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const iso=d=>d.toISOString().slice(0,10);if($('#pickupDate')&&!$('#pickupDate').value)$('#pickupDate').value=iso(today);if($('#returnDate')&&!$('#returnDate').value)$('#returnDate').value=iso(tomorrow);
$('#menuBtn')?.addEventListener('click',()=>$('#nav')?.classList.toggle('open'));$$('.nav a').forEach(a=>a.addEventListener('click',()=>$('#nav')?.classList.remove('open')));
$$('.ride-tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.ride-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}));
const toast=$('#toast');function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
$('#bookingForm')?.addEventListener('submit',e=>{e.preventDefault();showToast('Booking request received. Allino team will contact you shortly.')});$('#contactSubmit')?.addEventListener('click',()=>showToast('Message received. Allino team will contact you shortly.'));
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{const mode=btn.dataset.filter||btn.textContent.trim().toLowerCase();$$('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.vehicle-card').forEach(card=>{const type=(card.dataset.type||card.querySelector('.card-image span')?.textContent||'').toLowerCase();card.style.display=mode==='all'||type===mode?'block':'none'})}));
const localVehicleImages={alto:'assets/alto-cng.svg',wagonr:'assets/wagonr-cng.svg',dzire:'assets/dzire-cng.svg',activa:'assets/activa-6g.svg',access:'assets/access-125.svg',jupiter:'assets/jupiter-125.svg'};
function localizeVehicleImages(){ $$('img').forEach(img=>{const s=(img.getAttribute('src')||'').toLowerCase();const alt=(img.getAttribute('alt')||'').toLowerCase();let key=null;if(s.includes('alto')||alt.includes('alto'))key='alto';else if(s.includes('wagonr')||alt.includes('wagonr'))key='wagonr';else if(s.includes('dzire')||alt.includes('dzire'))key='dzire';else if(s.includes('activa')||alt.includes('activa'))key='activa';else if(s.includes('access')||alt.includes('access'))key='access';else if(s.includes('jupiter')||alt.includes('jupiter'))key='jupiter';if(key){img.src=localVehicleImages[key];img.classList.add('allino-product-image');img.removeAttribute('loading');}})}
localizeVehicleImages();
const heroImages=[['assets/alto-cng.svg','assets/activa-6g.svg','ALTO CNG'],['assets/wagonr-cng.svg','assets/access-125.svg','WAGONR CNG'],['assets/dzire-cng.svg','assets/jupiter-125.svg','DZIRE CNG']];let slide=0;const main=$('.main-vehicle img'),bike=$('.bike-photo img'),tag=$('.vehicle-tag');function showSlide(i){if(!main||!bike)return;slide=(i+heroImages.length)%heroImages.length;main.src=heroImages[slide][0];bike.src=heroImages[slide][1];if(tag)tag.textContent=heroImages[slide][2];$$('.dots i').forEach((d,n)=>d.classList.toggle('on',n===slide))}$$('.slider-arrow').forEach(b=>b.addEventListener('click',()=>showSlide(slide+(b.dataset.slide==='next'?1:-1))));if(main&&bike){showSlide(0);setInterval(()=>showSlide(slide+1),7000)}
