"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { adminSummary, currentUser, logout, type AllinoUser } from "@/lib/api";

const modules=[['Customers','Manage customer profiles, KYC and account status.','/admin/customers'],['Bookings','Track enquiries, confirmations, active trips and cancellations.','/admin/bookings'],['Fleet','Vehicles, availability, maintenance and damage records.','/admin/fleet'],['KYC','Review verification status and document workflow.','/admin/kyc'],['Enquiries','Website, corporate and long-term rental leads.','/admin/enquiries'],['Support','Customer support tickets and resolution tracking.','/admin/support']];

export default function Admin(){
  const router=useRouter(); const [user,setUser]=useState<AllinoUser|null>(null); const [stats,setStats]=useState({users:0,bookings:0,vehicles:0,pendingKyc:0}); const [error,setError]=useState("");
  useEffect(()=>{currentUser().then(u=>{if(u.role!=="ADMIN") throw new Error("Admin access required."); setUser(u); return adminSummary();}).then(setStats).catch(()=>{setError("Please sign in with an authorised admin account.");router.replace("/admin/login/");});},[router]);
  if(!user&&!error)return <main className="grid min-h-screen place-items-center bg-slate-100">Loading CRM…</main>;
  return <main className="min-h-screen bg-slate-100 text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/" className="text-2xl font-black">ALLINO <span className="text-sm font-semibold text-slate-400">CRM</span></Link><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-400 sm:block">{user?.email}</span><button onClick={async()=>{await logout();router.replace("/admin/login/")}} className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Sign out</button></div></div></header><div className="mx-auto max-w-7xl px-5 py-8"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">Operations</p><h1 className="mt-1 text-3xl font-extrabold">Admin Dashboard</h1><p className="mt-1 text-slate-500">Central control room for customers, bookings and fleet.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Customers" value={String(stats.users)}/><Stat label="Bookings" value={String(stats.bookings)}/><Stat label="Fleet" value={String(stats.vehicles)}/><Stat label="Pending KYC" value={String(stats.pendingKyc)}/></div><section className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{modules.map(([title,desc,href])=><Link key={title} href={href} className="rounded-3xl bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><h2 className="text-xl font-extrabold">{title}</h2><span className="text-blue-700">→</span></div><p className="mt-3 text-sm leading-6 text-slate-500">{desc}</p></Link>)}</section><div className="mt-8 rounded-3xl bg-gradient-to-r from-blue-800 to-slate-950 p-7 text-white"><h2 className="text-xl font-extrabold">Backend connected</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">These KPIs are loaded from the authenticated PostgreSQL/Prisma API. Customer and admin access are role-protected.</p></div></div></main>
}
function Stat({label,value}:{label:string,value:string}){return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
