import { assetPath } from "./assets";

export type Vehicle={id:string;slug:string;name:string;category:"Car"|"Bike";image:string;pricePerDay:number;fuel:string;transmission:string;seats:string;rating:number;availability:string;features:string[];description:string};
export const vehicles:Vehicle[]=[
{id:"alto",slug:"alto-cng",name:"Alto CNG",category:"Car",image:assetPath("/assets/alto-cng.svg"),pricePerDay:1800,fuel:"CNG",transmission:"Manual",seats:"4 Seats",rating:4.8,availability:"Available",features:["Unlimited KMs","CNG included","Insurance","24/7 Support"],description:"A practical, efficient city car for everyday Bhopal travel."},
{id:"wagonr",slug:"wagonr-cng",name:"WagonR CNG",category:"Car",image:assetPath("/assets/wagonr-cng.svg"),pricePerDay:2000,fuel:"CNG",transmission:"Manual",seats:"5 Seats",rating:4.8,availability:"Available",features:["Unlimited KMs","CNG included","Insurance","24/7 Support"],description:"Spacious and comfortable for family trips and city drives."},
{id:"dzire",slug:"dzire-cng",name:"Dzire CNG",category:"Car",image:assetPath("/assets/dzire-cng.svg"),pricePerDay:2200,fuel:"CNG",transmission:"Manual",seats:"4 Seats",rating:4.8,availability:"Available",features:["Unlimited KMs","CNG included","Insurance","24/7 Support"],description:"A refined sedan for comfortable business and leisure journeys."},
{id:"activa",slug:"activa-6g",name:"Activa 6G",category:"Bike",image:assetPath("/assets/activa-6g.svg"),pricePerDay:199,fuel:"Petrol",transmission:"Automatic",seats:"2 Seats",rating:4.8,availability:"Available",features:["Helmet support","Insurance","24/7 Support","Easy pickup"],description:"Easy, reliable scooter mobility for everyday city rides."},
{id:"access",slug:"access-125",name:"Access 125",category:"Bike",image:assetPath("/assets/access-125.svg"),pricePerDay:219,fuel:"Petrol",transmission:"Automatic",seats:"2 Seats",rating:4.8,availability:"Available",features:["Helmet support","Insurance","24/7 Support","Easy pickup"],description:"Comfortable 125cc scooter for longer city rides."},
{id:"jupiter",slug:"jupiter-125",name:"Jupiter 125",category:"Bike",image:assetPath("/assets/jupiter-125.svg"),pricePerDay:229,fuel:"Petrol",transmission:"Automatic",seats:"2 Seats",rating:4.8,availability:"Available",features:["Helmet support","Insurance","24/7 Support","Easy pickup"],description:"Smooth and practical scooter for Bhopal commuting."}
];
